import React from 'react'

import { Table } from '../components/table/index'

export function TableContainer({ children, ...restProps }) {
    return (
      <Table>
        <Table.Row>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
        </Table.Row>
        <Table.Row>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
        </Table.Row>
        <Table.Row>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
        </Table.Row>
        <Table.Row>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
        </Table.Row>
        <Table.Row>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
        </Table.Row>
        <Table.Row>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
        </Table.Row>
        <Table.Row>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
          <Table.Column>
            <Table.Text>Description</Table.Text>
          </Table.Column>
            </Table.Row>
            
      </Table>
    );
}